# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CompaniesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Companies'
  		@companies = Company.order(sort_order(:id)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View company'
      @company = Company.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new company'
    	@company = Company.new
    end

    def create
      @company = Company.new company_params
    
      if @company.save
        flash[:notice] = 'Company created'
        redirect_to casein_companies_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new company'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update company'
      
      @company = Company.find params[:id]
    
      if @company.update_attributes company_params
        flash[:notice] = 'Company has been updated'
        redirect_to casein_companies_path
      else
        flash.now[:warning] = 'There were problems when trying to update this company'
        render :action => :show
      end
    end
 
    def destroy
      @company = Company.find params[:id]

      @company.destroy
      flash[:notice] = 'Company has been deleted'
      redirect_to casein_companies_path
    end
  
    private
      
      def company_params
        params.require(:company).permit(:id, :name, :BPID, :address, :bi_customer_no)
      end

  end
end